name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }} and Poetry
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          python ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest --cov=web3_multi_provider -m "not integration" tests
