name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup poetry
      run: |
        curl -sSL https://install.python-poetry.org/ | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      env:
        POETRY_VERSION: 1.8.2

    - name: Install dependencies
      run: |
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest --cov=web3_multi_provider -m "not integration" tests
