name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v5

    - name: Setup Python and Poetry
      uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with pytest
      run: |
        poetry run pytest --cov=web3_multi_provider -m "not integration" tests
